### ISSUE TITLE
Code sync should resolve environment variables

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#1055]
A user reports:

```
ENV TARGET /usr/local/app 
COPY src $TARGET
```

Using the above, there will not be a /change agent registered for the target location. 
If you change the COPY to use the path directly, it will work.

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix code sync env var support](https://trello.com/c/aSmtMZYM/1152-fix-code-sync-env-var-support)

**Comment by MiguelMoll** [comment]
Fixed via #1444

**Comment by idris** [comment]
@MiguelMoll there seems to have been a regression on this.  I'm on client version `20170127170143` and I had to change back to using the absolute path in my Dockerfile instead of the env variable.  Otherwise files were not being sync'd properly.

My colleague is seeing the same issue on client version `20161215133928`.

**Comment by MiguelMoll** [comment]
Thanks for the heads up @idris. I'll check it out and see why our tests didn't catch something.

**Comment by MiguelMoll** [comment]
If/when you can, could you create a new issue explaining your use case? Perhaps including your Dockerfile. Tests are working for the cases given. Could be we missed one.
