### ISSUE TITLE
add service for cloudfront

### ISSUE THREAD

**Issue by contra** [convox/rack#1198]
ability to spin up new cloudfront distributions (+ do domains/ssl)

**Comment by joelpresence** [comment]
+1

We would actively use this, because we'd want the cloudfront distribution to point to ELB that Convox creates and spins up.

Currently, if we have a Route 53 CNAME pointing to an existing Cloudfront distribution, can Convox point that existing Cloudfront distribution to the ELB that Convox creates?

**Comment by ddollar** [comment]
Convox is currently only taking feature requests for Generation 1 through support tickets on paid accounts. That being said, I'd happily merge a pull request adding this resource.
