### ISSUE TITLE
Ability to use custom SSL cert with `convox start`

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#1332]
A user writes:

> is it possible to inject a valid ssl certificate for local development? We have one for local dev that we need for some strict chrome requirements...

**Comment by baversjo** [comment]
I asked this because service workers requires a valid ssl certificate to start. While this can be disabled using a chrome flag, this gets harder when trying to test an app on android devices. We're not using service workers right now though but something to consider.

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ability to use custom SSL cert with `convox start`](https://trello.com/c/Q8stccqD/871-ability-to-use-custom-ssl-cert-with-convox-start)

**Comment by bisrael** [comment]
this would also be a great to have for deployment, so we can specify a cert for the load balancer to use instead of a self-signed cert

suggested syntax would be a line in `labels:` like `- convox.port.443.cert= arn:...`

**Comment by mwarkentin** [comment]
@bisrael Just checking that you've seen the existing [cert support](https://convox.com/docs/ssl/)?

**Comment by bisrael** [comment]
@mwarkentin yes, that solves my issue, thanks!

**Comment by codyaray** [comment]
+1 for the ability to inject an SSL cert.

Our use case is that our corporate overlords MITM (almost) all of our traffic with a self-signed cert. We have installed our root installed locally on our machines but the work done in Docker containers locally obviously doesn't have this cert installed. Although I'm not sure if `init` and `doctor` use containers, that's my current self-diagnoses here.

In any case, we get a bunch of "certificate signed by an unknown authority" errors during `convox init`, `convox doctor` and the like. For example:

```
$ convox init
Initializing unknown
Writing Dockerfile... OK
Writing docker-compose.yml... OK
Writing .dockerignore... OK
segment 2016/11/28 09:32:11 error sending request: Post https://api.segment.io/v1/batch: x509: certificate signed by unknown authority
```

When viewing this Segment URL in the browser, I can see the Root Cert is our corporate self-signed cert, there's an intermediate cert that we own, and then a *.segment.io cert. The Root Cert is marked as trusted for all users in either Chrome or the OS (haven't looked to see where its configured) so my browser doesn't complain, but the convox CLI does.

Ironically, we're looking to Convox because we're such a security conscious group. :)

**Comment by codyaray** [comment]
Another option would be to provide a flag like AWS to ignore this kind of error.

**Comment by orangewolf** [comment]
What would the core team think about swapping convox/proxy for something more akin to (or may that just is) [dinghy-http-proxy](https://github.com/codekitchen/dinghy-http-proxy)?  

This would:
- Get the custom SSL issue resolved
- Allow for web.myapp.docker local DNS entries
- Eliminate the need for port offsets when running multiple apps via convox start. 

If there is interest, I'd be happy to see if I can dig in and figure out how to make that work. (if you'd rather stay with the simpler proxy, I can understand that too).
