### ISSUE TITLE
Rollback or better handling of failing release

### ISSUE THREAD

**Issue by asyazwan** [convox/rack#182]
When a release builds successfully but is non-functional, it's trivial to check that the ELB has 0 instance. Notify and rollback to previous release automatically. Otherwise downtime will be longer than necessary.

**Comment by nzoschke** [comment]
This is a great feature request, and I plan to do this soon in another pass on notifications.

**Comment by nzoschke** [comment]
Thanks for your patience, plenty of other issues have taken precedence to this.

#429 reminded me about this issue, which still needs design and engineering.

Based on lots of experience debugging bad deploys based on app level problems, I picture something like:

* Convox picks a max deployment window value, say 15 minutes
* After a `convox deploy` we poll the describe service API and look at the deployments and events for the next 15 minutes
* If all the process services converge back to a single Primary deployment and have a steady state event, consider the deployment good
* If after 15 minutes one or more of the service deployments did not converge, consider the deployment bad
* Automatically roll back the app to the previous release
* Send a notification about a deployment rollback

There are still a lot of gotchas here: 

* Is 15m right? 
* Is an async notification the right way to inform of this problem?
* Is the rollback a safe and reliable way to correct the problem?
* What if the rollback also fails in general? 
* What if the operator did things like database migrations that also need to roll back?

**Comment by anthonyrisinger** [comment]
I've had this flagged for days trying to collect thoughts about it... I don't think I'd personally like it automatically rolling back. I did at first but the "What if the operator did things like database migrations" part makes me think that rolling back is highly dependent on the circumstances of promotion. The operator could have already updated sibling apps or something and rolling back doesn't make sense (although it probably doesn't make the situation any worse in most cases either).

At the same time, this is effectively what CF already does if an app hits the `UPDATE_ROLLBACK_COMPLETE` state. So this is already happening in some cases, just not for ECS-related things because `cmd/formation` doesn't wait for convergence. Once we start using the native ECS CF resource type, my *guess* is the stack might not signal completion until ECS reaches convergence, so this behavior might already be in the pipeline, handed down from AWS.

In light of the above, it might be worth checking how the new ECS CF resource behaves before making a decision. If convergence *does not block* the stack update (stack is considered `UPDATE_COMPLETE` even though ECS is not 100% done rolling out a deployment) then I'd suggest rolling back by default (to match what CF occasionally does anyway) but adding a flag like `--force` or something to prevent rollback. However, if the new resource *blocks* the stack update until ECS convergence is complete, then there is no need for a flag because it won't be viable anyway (the ECS CF resource will always rollback on failed updates without convox being involved).

**Comment by anthonyrisinger** [comment]
In case it wasn't clear, rolling back seems the natural thing to do, even though it makes me feel a little uneasy for reasons I can't fully articulate. Adding a flag to prevent rollback on promotion or deploy would be nice, if possible. 15m seems OK to me since that's the same timeout given to EC2 instances when they are rolled. Mostly I think we should test how the new ECS CF resource behaves and copy that.

**Comment by ddollar** [comment]
Failed releases now roll back
