### ISSUE TITLE
`convox deploy` of apps without a docker-compose.yml point to `convox init`

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#1905]
Right now it's very easy to deploy an app that has no chance of working. Like an empty directory:

```sh
$ mkdir myapp && cd myapp
$ convox deploy
Deploying myapp
Creating tarball... OK
Uploading: 177 B / 32 B [================================] 553.12 % 0s
Starting build... OK
Authenticating 132866487567.dkr.ecr.us-east-1.amazonaws.com: Login Succeeded
ERROR: open /tmp/464976966/docker-compose.yml: no such file or directory
ERROR: myapp build failed
```

We can offer a better experience by:

- [ ] Changing the feedback to a friendly "ERROR: No docker-compose.yml found. Try `convox init` to generate one."

We should consider even more pre-flight validation of the manifest.

- [ ] If docker-compose.yml is present, validate that it is compatible before building and releasing it.

**Comment by ddollar** [comment]
Currently if you `convox deploy` without a `docker-compose.yml` we happily proceed until the builder fails with a weird error message about `/tmp`.

Instead of auto-init we could show an early error message instead:

```
$ convox deploy
No docker-compose.yml found. Try `convox init` to generate one.
```

Advantages over auto-init:
* If you type `convox deploy` in your home directory by accident we don't a) try to identify the app type of your home directory or b) write a useless docker-compose.yml into your homedir.
* Helps the user understand what's going on. `convox init` makes the new files visible immediately where they can be poked at.
* Simplifies the code.
* I would not immediately guess that `convox deploy` would write to the filesystem. I can easily see us adding prompts and guards here to work around this in the future all of which will be complicated.

Disadvantages:
* Extra step for new apps

**Comment by nzoschke** [comment]
That design sounds good too. Clear error messages with next steps are good.

Should `convox start` follow the same pattern?

```
$ convox start
No docker-compose.yml found. Try `convox init` to generate one.
```

**Comment by nzoschke** [comment]
And perhaps `convox deploy` can do some manifest validation before building too?

```sh
$ convox deploy
Deploying myapp
Creating tarball... OK
Uploading: 177 B / 32 B [================================] 553.12 % 0s
Invalid docker-compose.yml found. See https://convox.com/docs/preparing-an-application/ for more information.
```

**Comment by ddollar** [comment]
`convox deploy` should be able to do manifest validation locally before pushing the same way that `convox start` does.

**Comment by ddollar** [comment]
Might have to tweak a bit about the env var validation.
