### ISSUE TITLE
Convox logs issue

### ISSUE THREAD

**Issue by chuckxwu** [convox/rack#1955]
When I run convox cli tools to check rack logs, I run into the following error.

chuckwu@xiangjun-3 ~$ convox logs  --rack convox-demo
ERROR: chuckwu not found

My CLI version is as shown below.
$ convox --version
client: 20170217164723
server: 20170216230221 (convox-demo-1082331502.us-east-1.elb.amazonaws.com)

**Comment by hnrc** [comment]
Looks like you have to specify the app name (with the `--app` param). The CLI uses your current working directory as the app name if it's not explicitly specified.

**Comment by MiguelMoll** [comment]
To view a rack's log, you'd run `convox rack logs`.

To view an app's log, you'd run `convox logs` with an optional `--app` argument otherwise the current working directory is used as the app name.

Please let me know if this isn't the behavior you're seeing. Perhaps the CLI help message should do a better job of stating this.
