### ISSUE TITLE
ECS can not start with non-root user with env

### ISSUE THREAD

**Issue by chuckxwu** [convox/rack#1972]
Hello,

I try to launch ECS task via convox with non-root user with environment variables I specified.

But it seems like there is no option to specify non-root user running and inject environment variables I set in .env file.

Can you help check it?

**Comment by MiguelMoll** [comment]
`.env` is only used by `convox start` for local development. Once an app has been deployed, environment variables are set via `convox env set`. An example would be `convox env set FOO=bar`. Since you do have a `.env` file, a shortcut could be `cat .env | convox env set`. That command reads from standard input and sets the variables accordingly. Running `convox env` afterwards to confirm the variables are set correctly.

If you're looking for default values, docker-compose.yml would be the place to set them.
The [docs](https://convox.com/docs/environment/) go into more details. Please let me know if I misunderstood the question.

**Comment by chuckxwu** [comment]
No such issues anymore.
