### ISSUE TITLE
Convox log on BuildInstance Rack fails

### ISSUE THREAD

**Issue by markfermor** [convox/rack#2004]
When running convox logs on the buildinstance rack we get errors. 
```
convox logs --rack [build rack name]
ERROR: websocket.Dial wss://console.convox.com/apps/[app name]/logs: bad status
```

After brief chat with Matt Manning on the public convox slack channel, it seems this is something that isn't implemented yet. It might be a useful feature to make available, to be able to see full rack logs
`convox builds logs <build ID>`

**Comment by soulshake** [comment]
Having trouble reproducing this. Is it still the case for you?

**Comment by MiguelMoll** [comment]
@markfermor Thanks for the feedback. I'm not sure I follow what's going on. I believe you want insight into failed builds that take place on a build instance? They are streamed while a build is taking place and, as you mentioned, are visible via `convox builds logs BUILD_ID`.

Rack logs are accessible via `convox rack logs`. But since there is no rack running on the build instance, there's nothing to specify via the logs command. What kind of logs/information are you interested in?
