### ISSUE TITLE
Feature: GitHub status check-dependent Workflows

### ISSUE THREAD

**Issue by soulshake** [convox/rack#2031]
Feature request: allow configuring Workflows to only trigger if status checks on Github have passed.

**Comment by FWMatt** [comment]
Thanks for filling this - really keen to get this in Convox.

Once its available we can hook our master branch up to deploy directly to production via Convox.

**Comment by MiguelMoll** [comment]
This is a nice feature to have. As this is a feature for Console, I'll go ahead and add this issue there.

Closing this one for now but please keep the conversation here going if needed.

**Comment by FWMatt** [comment]
@MiguelMoll could you link me to the new issue on Console please?

**Comment by MiguelMoll** [comment]
The Console repo and it's issues are private. Unfortunately I have nothing else to share about it at the moment. We'll try to update this issue in the future once we have something to share.

Another option would be to open a support ticket via Console and keep track of it that way.

**Comment by FWMatt** [comment]
We are really loving Convox, but the support seems to be quite disconnected. There is
* a GitHub repo
* the support tickets on the Console
* Intercom
* Slack channel

I've been asked to raise issues in different places - its not clear to me what the best channel is. 

If you close my issue here I have no way of tracking it. Whats my incentive to therefore post it?

**Comment by mattmanning** [comment]
Hey @FWMatt. I'm really sorry for the confusion here. The definitive best place for feature requests and bug reports is via support tickets on the Console.

It makes sense to close this issue because it's not material to this particular repo, but we do want you to be able to track the issue.

To make things easy you can open a ticket there with simply a link to this issue. I'll make sure it also gets internally linked to the Console issue and that we notify you when there are any changes in status.
