### ISSUE TITLE
getting process logs from API

### ISSUE THREAD

**Issue by contra** [convox/rack#2071]
Trying to grab the logs for a specific process (by id) - is this possible using the API?

**Comment by MiguelMoll** [comment]
Not currently. There might be something here we could do with the `"/apps/{app}/logs"` websocket call and filtering for the process ID. But that would require a change to include the process ID instead of the container ID.

**Comment by contra** [comment]
@MiguelMoll Is there any API for logs atm? How does the CLI get logs?

**Comment by MiguelMoll** [comment]
There is an API to stream app logs through a websocket. This is the controller that handles it: https://github.com/convox/rack/blob/40b2e1e2cb2ca08f66d63445798339ada36ab2d9/api/controllers/apps.go#L126

Parameters of interest:
- filter: look for a specific string
- follow: keep streaming or not
- since: e.g get logs 30m(inutes) back

**Comment by contra** [comment]
@MiguelMoll So since the process ID isn't in the logs that can't be filtered either. Hmm.
