### ISSUE TITLE
CLI: .env warning when inverting ignore mechanism

### ISSUE THREAD

**Issue by eladidan** [convox/rack#2303]
It's common practice to setup `.dockerignore` with the following pattern: 
```
*
.*
!<path that should be included>
!...
```

Essentially this ensures that all files are ignored by default unless explicitly included.
When packaging docker this way however, we get the following warning from convox cli  when deploying:

>WARNING: You have a .env file that is not in your .dockerignore, you may be leaking secrets

Does the `.env` actually end up in the tarball this way because convox doesn't parse the ignore file correctly or is the warning simply looking for an explicit `.env` ignore instead of verifying that it isn't in the tar?
The former is obviously more alarming but from testing with `convox start` it does not seem to be the case.

**Comment by ddollar** [comment]
Not sure what's going on here but if you figure it out would happily accept a PR fixing it.

**Comment by exalted** [comment]
I think `convox build`, while uploading the tarball to your Rack, isn't working exactly as we expect; meaning its behavior is different than what `docker-compose build` reads from the current working directory.

A simple `.dockerignore` file that contains:

```
*
!docker-compose.yml
!Dockerfile
!foobar/app/
```

Apparently will not "upload" `foobar/` (or `foobar/app/` for that matter), because right after the upload phase is over, here's the kind of error I get:

```
Deploying myapp
Creating tarball... OK
Uploading:  19.53 MiB / 19.53 MiB [======================] 100.00% 28s
Starting build... OK
Authenticating 824758182196.dkr.ecr.us-east-1.amazonaws.com: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded

ERROR: mkdir /tmp/034435876/foobar/app: no such file or directory
ERROR: myapp build failed
```

This is prior to `Dockerfile` getting parsed & run, I believe. Not sure at this point what's being uploaded (see `19.53 MiB` above) at this point. Any way to "debug" this?

**Comment by ddollar** [comment]
The current CLI is using Docker's own library for dockerignore

**Comment by exalted** [comment]
Hi @ddollar thanks for getting back into this! 🙇 

> The current CLI is using Docker's own library for dockerignore

… meaning, now the behavior should be coherent for both `docker-compose build` and `convox build` please?
