### ISSUE TITLE
Placement Groups

### ISSUE THREAD

**Issue by jontonsoup** [convox/rack#2311]
Is there any interest in setting up placement groups? It's better for microservices.

**Comment by jontonsoup** [comment]
Ah thanks! Didn’t see that

**Comment by jontonsoup** [comment]
Actually, my concern is more about how servers are placed than tasks. 

I’d love for racks to be placed close to each other so my microservices have lower latency. Unfortunately, we need strong VPC barriers between the ones that speak to third parties so everything can’t be in the same rack.

**Comment by mwarkentin** [comment]
@jontonsoup Ah interesting - would you want all of your apps and containers to be in a single-AZ?

**Comment by jontonsoup** [comment]
I’m not exactly sure what the best tradeoff in terms of availability and speed is here. We’d love the speed, but not having the added redundancy of availability zones makes me a little uncomfortable. 

Do you see a way to have both via some sort of fallback scheme?

**Comment by mwarkentin** [comment]
Not really - placement groups are restricted to a single AZ - ECS placement strategies could let you run containers within only a single AZ, but then you would have the rest of the rack capacity going unused (and not sure how that would react to that AZ going out since you were asking those tasks to run specifically on that AZ).

FWIW, we definitely fall on the availability side of this equation - the latency between AZs is not significant for us (I believe it should be `<10ms` between AZs.

**Comment by jontonsoup** [comment]
Yea I think that probably is the better side to fall on. 

Ok that makes sense— just wanted to start a conversation on it!

**Comment by ddollar** [comment]
Closing this for now as the AZ latency is so small compared to the complexity something like this would add.
