### ISSUE TITLE
How can I make my apps promote faster?

### ISSUE THREAD

**Issue by paulkernfeld** [convox/rack#2401]
Right now, waiting for an app to finish promoting accounts for about 50% of the latency in my CD process. If I could decrease this, then my Convox deploy latency would be competitive with Heroku.

So far, the only change that I've made to my default configuration is to set `convox.health.timeout=10` since my apps boot pretty slowly.

For context, I'm working in Scala. Right now, when I merge a commit for release, the time breakdown looks about like:

- 150 seconds: Docker build (from `Promoting RBLAHBLAHBL... OK` until completion)
- 90 seconds: Scala compile, unit tests, and build
- 30 seconds: Docker build (from `Starting build... OK` until `Promoting RBLAHBLAHBL... OK`
- 30 seconds: creating and uploading tarball (from `Creating tarball...` until `Starting build... OK`)

**Comment by mwarkentin** [comment]
@paulkernfeld have you tried out the minimum healthy percentage configurations? We find that dropping that to 75% speeds up our deploys a lot (as a few extra healthy containers can be dropped immediately to help make room for the new ones that need to spin up).

**Comment by paulkernfeld** [comment]
Ah, I left out an important part of my situation: this is for an application that only runs a single container (two during deploy, I think). So I don't think that changing the healthy percentage would be useful in this case.

**Comment by mwarkentin** [comment]
Ah, good to know! A few other things:

* Are you using a build instance? This will let you leverage the docker cache for convox builds to get more cache hits.
* Potentially you could build and upload an image outside of convox, and then use `image` instead of `build` to skip the build step

**Comment by paulkernfeld** [comment]
Perhaps I'm misunderstanding your advice, but I was hoping to shorten the app's promotion time, not the build time. Would using a build instance help with this?

**Comment by mwarkentin** [comment]
Ah, sorry - saw `150 seconds: Docker build` and thought that's what you were trying to fix. :)

Promotion is basically the amount of time for the desired number of new containers come up and be healthy so the old ones can be killed.

Do you have enough headroom on the cluster for the new container to start before the old one is killed?

If so, I think you need to improve the application start up time if possible so that it can signal that it's healthy earlier. Perhaps by provisioning more cpu / memory or using a better instance type?

Do you know how long your app takes to start within a container?

You could also look in the ECS events for the service to see if anything sticks out that is causing it to take so long.

**Comment by paulkernfeld** [comment]
My apologies, I could have written that more clearly! By the way, thanks very much for your helpful responses!

I believe that my new container is indeed coming up before the old one is being killed (see the logs below).

My app claims that it is only taking five seconds to start up, so it seems like that isn't the bottleneck.

Here are two questions:
1. What is happening between 09:23:36, when I see `UPDATE_IN_PROGRESS`, and 09:24:30, when I see my first app logs?
2. What is happening between 09:24:35, when my app claims that it is listening, and 09:25:38, when I see `UPDATE_COMPLETE`?

Below is a snippet that interleaves my CLI, rack, and application logs. I've tried to remove irrelevant information, but if I've left anything important out I will be happy to retrieve that information!
```
Dec 08 09:22:22 Deploying booker
Dec 08 09:22:24 Creating tarball... OK
Dec 08 09:22:41 Uploading: ...
Dec 08 09:23:00 Authenticating blah.dkr.ecr.us-west-2.amazonaws.com
Dec 08 09:23:00 Login Succeeded
Dec 08 09:23:02 Successfully built 12345678 
Dec 08 09:23:02 Successfully tagged booker/booker:latest
Dec 08 09:23:02 running: docker tag ...
Dec 08 09:23:03 running: docker push ...
Dec 08 09:23:11 blahblah: Pushed
Dec 08 09:23:14 Release: RBLAHBLAH
Dec 08 09:23:17 Promoting RBLAHBLAH
Dec 08 09:23:17 system:20171201042926/aws/cloudformation UPDATE_IN_PROGRESS staging-convox-booker User Initiated
Dec 08 09:23:24 system:20171201042926/aws/cloudformation UPDATE_IN_PROGRESS BalancerBookerInternal 
Dec 08 09:23:25 system:20171201042926/aws/cloudformation UPDATE_COMPLETE BalancerBookerInternal 
Dec 08 09:23:25 system:20171201042926/aws/cloudformation UPDATE_IN_PROGRESS BookerECSTaskDefinition 
Dec 08 09:23:31 system:20171201042926/aws/cloudformation UPDATE_IN_PROGRESS BookerECSTaskDefinition Requested update required the provider to create a new physical resource
Dec 08 09:23:32 system:20171201042926/aws/cloudformation UPDATE_COMPLETE BookerECSTaskDefinition 
Dec 08 09:23:36 system:20171201042926/aws/cloudformation UPDATE_IN_PROGRESS ServiceBooker 
Dec 08 09:24:30 service/booker:RBLAHBLAH/12345678 first logs from app appear
Dec 08 09:24:35 service/booker:RBLAHBLAH/12345678 app says that it is listening
Dec 08 09:25:38 system:20171201042926/aws/cloudformation UPDATE_COMPLETE ServiceBooker 
Dec 08 09:25:41 system:20171201042926/aws/cloudformation UPDATE_COMPLETE_CLEANUP_IN_PROGRESS staging-convox-booker 
Dec 08 09:25:44 system:20171201042926/aws/cloudformation DELETE_IN_PROGRESS BookerECSTaskDefinition 
Dec 08 09:25:47 system:20171201042926/aws/cloudformation DELETE_COMPLETE BookerECSTaskDefinition 
Dec 08 09:25:47 system:20171201042926/aws/cloudformation UPDATE_COMPLETE staging-convox-booker 
Dec 08 09:25:47 Waiting for RBLAHBLAH... OK
```

**Comment by mwarkentin** [comment]
I believe that `UPDATE_COMPLETE` is when ECS has signalled back to Cloudformation that the resource has been updated (eg. all new containers are healthy and old containers have been cleaned up). There may be some improvements you could see by reducing threshold for the health check on the app? Maybe if you check that more often it would come up sooner?

Otherwise I think this is kind of just dependent on the way Cloudformation / ECS interact? Maybe there's a way to get Cloudformation to do more in parallel like update the load balancer and the task definition at the same time? Just a random guess there really..

**Comment by ddollar** [comment]
The easiest ways to make promotes happen faster are to add more instance capacity or to switch to Gen 2. The rest is really in Amazon's hands.

**Comment by exalted** [comment]
> The easiest ways to make promotes happen faster are to add more instance capacity or to switch to Gen 2. The rest is really in Amazon's hands.

@ddollar how does gen2 helps with faster promotes compared to gen1 please?
