### ISSUE TITLE
Allow the use of N ALB instead of just one

### ISSUE THREAD

**Issue by phuongnd08** [convox/rack#2750]
Since it's unclear if AMZ is going to allow more than 100 rules per ALB, convox can allow user to specify the number of ALB.
If there is N ALB, the rules should be split between ALBs.

Perhaps an easy way is to hash the app name and then mod it by N to determine which ALB the rules for that app will be defined in. This would result in approximately N times increase in number of possible rules while keeping the ALB address per app stay fixed when the number of app increases. It does have a drawback that when changing N the ALB address of an app will change to but I guess this is the price to pay to use a giant cluster to host many micro apps.

**Comment by ddollar** [comment]
I don't think it's a good idea to add this kind of complexity when the issue can (will?) be fixed by AWS increasing an artificially low limit. There are other temporary workarounds (InternalDomains=No) that can relieve the pressure for now. If you really run out of rules even using that param then it would be best to create multiple racks.
