### ISSUE TITLE
Injected convox env dependency on bash breaks alpine based images

### ISSUE THREAD

**Issue by agonbina** [convox/rack#2937]
The injected convox env `entrypoint.sh` script depends on having bash in order to execute before the start command. However, bash is not present in most `alpine` docker image builds(I can confirm this for the official `node` alpine docker images), which means that the docker image fails to run and you get a very cryptic error message: `exec user process caused "no such file or directory"`

I strongly recommend that this is documented properly such that users are aware that bash is a required dependency to any final docker image that they run their service on. I have (sadly) spend more than a few hours trying to understand the cryptic error message and solve the issue.

**Comment by ddollar** [comment]
The problem is actually not bash, the problem is the alternative libc used by alpine (musl). This requires static binaries to be built using a special set of flags for alpine.

https://github.com/convox/rack/pull/2936 will fix this issue and should be rolling out a bit later today.

That being said I do recommend avoiding alpine in general. I used to use alpine-based images but got bitten by libc-related issues like this enough times that I no longer do so.

**Comment by agonbina** [comment]
Thanks @ddollar, can confirm that the issue was resolved in the latest convox release.
