### ISSUE TITLE
Support for Proxy Protocol at ELB

### ISSUE THREAD

**Issue by mtrofimm** [convox/rack#320]
http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html

**Comment by kaaloo** [comment]
I'm working on this as a learning experience (which is also of pratical use for me) because I'm interested in using socket.io and ran into the issues outlined here:

[https://medium.com/@Philmod/load-balancing-websockets-on-ec2-1da94584a5e9#.ut2oqbiez]()

My work is on this branch:

[https://github.com/kaaloo/rack/tree/elb-proxy-protocol]()

Comments welcome!

**Comment by nzoschke** [comment]
This was merged in https://github.com/convox/rack/pull/464
