### ISSUE TITLE
Creating Redis Service doesn't support a custom instance type

### ISSUE THREAD

**Issue by johnboy14** [convox/rack#340]
Currently when creating a Redis service, there are no options to specify an instance type argument when using the CLI.  We just get the micro instance by default.

**Comment by matthewford** [comment]
@johnboy14 yup, same with the db - for prod we're manually provisioning our databases

**Comment by nzoschke** [comment]
It actually does! It just hasn't been documented / discoverable.

```
$ convox services create redis --instance-type=cache.t2.small
$ convox services create postgres --instance-type=db.t2.small
```

Without --instance-type, they default to t2.micros.

I am closing this since it's actually supported. You can follow https://github.com/convox/rack/pull/428 for progress and to give feedback on improvements.

Here's a sketch of new usage that will land on that PR:

```
$ convox services create
convox services create: create a new service

Usage:
  convox services create <type> [--name=value] [--option-name=value]

Supported types / options:
  mysql       [--allocated-storage=10] [--instance-type=db.t2.micro] [--multi-az]
  papertrail  --url logs1.papertrailapp.com:11235
  postgres    [--allocated-storage=10] [--instance-type=db.t2.micro] [--multi-az]
  redis       [--instance-type=cache.t2.micro]
  webhook     --url=https://grid.convox.com/rack-hook/1234
```
