### ISSUE TITLE
ELB naming convention changes based on number of processes in docker-compose

### ISSUE THREAD

**Issue by soulware** [convox/rack#381]
We had a docker-compose with 2 processes specified (both exposing ports). 
The 2 ELBs were named based on combination of app and process name - 
  - `<app>-<process1>`
  - `<app>-<process2>`

But if we remove one of the processes from docker-compose we discovered the
ELB for the remaining process was actually replaced due to the naming convention changing - 
  - `<app>`

This happened on the __subsequent__ deploy not the deploy that originally removed the 2nd process.
Took us by surprise because suddenly the endpoint of the remaining ELB changed for reasons completely unrelated to the contents of that deploy.
 
It would be nice if the existing ELB did not change.
If it did have to change - it would be preferable to update it on that associated deploy and not the subsequent one.

**Comment by xtfxme** [comment]
I'll let someone else expand more if need be, but this is essentially the same bug described by https://github.com/convox/rack/issues/354#issuecomment-185426729 albiet manifested slightly different. It is fixed for new apps by #341 (release 20160223211445 or greater) but it's not likely to be fixed in for existing apps.

The timing and ordering around your deploys sound a little funny to me (maybe there is more to be done) but the legacy behavior causing bad ELB name changes should no longer be a problem.

**Comment by nzoschke** [comment]
Thanks for the report.

Yes, there was surprising behavior around ELB naming/renaming until a couple days ago.

The design goal is to keep ELB names very stable for an app, process type and scheme (internet-facing vs internal).

Please `convox rack update` to 20160223211445  or greater. Then recreate a your app (inconvenient, I know :frowning:) to get new logic where the ELB never changes until the process name changes or the port mapping changes from internal to external (80:80 -> 80).
