### ISSUE TITLE
Unable to deploy after scaling process to max

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#429]
Will try to reproduce next week - but while testing we ended up in a situation where we did a deploy and ECS was unable to find any instances to start new processes - it seemed like because we had maxed out (3x tasks on 3x instances) - ECS was waiting for an open instance to start launching the new release tasks and then start killing the old ones, which was never happening.

From memory:

* Created app w/ 1 `main` process + 1 redis process
* Scale `redis` to 0
* Scale `main` to 2
* Scale `main` to 3
* `convox deploy` (no code changes, but deploy worked)
* ECS started complaining about port `8080` already being in use, unable to place container, etc.

I'll fill in some more details when I have a chance.

Expected result: old containers were killed and replaced by the new ones in a non-downtime fashion (since we had more than 1 process deployed).

**Comment by mwarkentin** [comment]
CC @nduthoit

**Comment by nzoschke** [comment]
This is a common challenge on ECS. You can update a Service with a new TaskDefinition or DesiredCount with no guarantee that it will be able to find capacity for new containers. ECS will keep retrying forever.

I definitely want Convox to help you with this.

One idea is to automatically roll back the `convox deploy` if it doesn't execute completely within a window. There is an issue for that here that needs to be fleshed out more: https://github.com/convox/rack/issues/182

But I think we can avoid auto-rollbacks for capacity related issues. In this case, DeploymentConfiguration minimumHealthyPercent setting is the key:

http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentConfiguration.html#ECS-Type-DeploymentConfiguration-minimumHealthyPercent

By default this is 100%. ECS keeps all the old container running to satisfy 100%, and has to successfully find capacity and start a new container before it will stop an old one.

We need a design for setting this to less than 100%. It could be:

* Always 100% and the convox API prevents you from scaling main=3 if you don't have 3+1 instances
* By default 100% but you can configure it per process type
* By default 50%
* Set dynamically to be DesiredCount - 1 (i.e. 2 => 50%, 3 => 66%)

**Comment by mwarkentin** [comment]
I think my preferences in order would be 4, 2, 1, 3

* I like being able to use all of my available instances for a specific process (maybe this becomes less of an issue if AWS fixes ELB to support multiple ports for a process on a single instance)
* It might be nice to default to `DesiredCount - 1`, but allow the `1` to be set per process - if I have a large number of containers running (eg. 15), a deploy could take quite a while if it's replacing 1 at a time - instead I could change it to do 3 at a time
* Removing 50% could be dangerous - if I have 20 containers because I need around that much to handle my traffic, and 10 are dropped for a minute or two, it could cause performance issues, etc.
* re: default 100% but customizable: I think convox should be able to handle the 100% instance use case out of the box

**Comment by xtfxme** [comment]
My thoughts here were also leaning toward a dynamic solution that adjusts `minimumHealthyPercent` pretty much exactly as described here.

I think @mwarkentin has a good point about 50% not being enough to handle the load. It's very likely that extra process copies beyond 2-3 exist for reasons other than redundancy. However, I also think that convox could make some general assumptions, such as the the user has configured the process to support expected load + 20% buffer, ie. `minimumHealthyPercent` should not drop blow 80% to continue supporting the load. In the example of 15, this would allow 3 slots for deployment and ensure 12 are always up.

On the flip-side, I'm not going to be heartbroken if I have to manage this number explicitly per-process, since it is intimately tied to how I expect the process to behave... I can't however think of a concrete situation from past experience where the 80% falls down, necessitating manual control. In general I think more "knobs" are a burden and should be avoided.

**Comment by mwarkentin** [comment]
We recently added something similar to speed up deploys in our own fabric-based deploy toolkit - we count the number of servers to be replaced and never remove more than 33% at a time. I'd be good with choosing a default between 20-33% and sticking with that - off the top of my head I don't think that would cause major problems with any of our apps.

**Comment by nzoschke** [comment]
There's one other option available today... Set the `Autoscale` parameter to `Yes`.

With this, Convox will dynamically add a new instance. This will take longer than you might expect but the deployment will eventually finish.

**Comment by nzoschke** [comment]
Yeah, I've been thinking about "knobs" a lot. In the AWS CloudFormation world this is very literally "Parameters". The goal is to require no customization for most folks day to day usage, but to maintain some control for special use cases. In practice this looks like having as few Parameters as possible and very good defaults for them.

I like the `minimumHealthyPercent` of 80 - 66% suggestion. That's a sensible default that takes into consideration service availability, resource utilization and deployment speed.

This makes sense to introduce as a per process parameter with a default to me. I don't want to think about it almost anywhere, except for a few experiments.

**Comment by anthonyrisinger** [comment]
I'm maybe a little conservative(?) on this front, but 66% feels a bit small because that means I have to keep 1/3 extra capacity around to deal with deployments that don't happen all that often. In the past (on Mesos + Marathon) it was not uncommon for us to have a process with 10-20 copies running. 80% requires only 1/5 extra... maybe 75% at 1/4 extra is a compromise? I know it's closer to my preferred 80% than 66%, but it's also a nice/easy/natural number to tell people, eg. "make sure you keep an extra 25% lying around". Not too big of deal either way since it'll be configurable, but that's my thoughts on the default.

Special cases would then be things under 4 instances (if we decided to go with 80% or 66% as the default, this still applies):

* 5+ instances generate 75% (this would be 80% if 80% is the base)
* 4 instances generate 75%
* 3 instances generate 66%
* 2 instances generate 50%
* 1 instance generates 0%

I'd like to see the 1 instance case handled properly both here and for the rack itself because I often use single host racks for CI and testing as they are cheaper, faster, and simpler to reason about. Currently single host racks are unable to update themselves or the apps they host without manually killing tasks because there is no way to make good on the 100% `minimumHealthyPercent` (or anything above 0% for that matter).

I'm not sure how feasible this is without `Autoscale`, but it would be nice if we could handle the 1 instance case (maybe others) in a slightly nicer way... if the rack has the capacity and hosts, it's ok to use 100% `minimumHealthyPercent` because the new instance will be placed on a different host. I'm sort of rambling here because I also feel that if you only have 1 copy running, convox should be able to assume you don't care about HA, and that makes everything work correctly without fragile heuristics or babysitting by the convox api (CF will just kill the old proc and schedule a new one with minor downtime).

**Comment by mwarkentin** [comment]
Looks like these parameters are now exposed for manual tweaking in https://github.com/convox/rack/pull/641

Would probably still be nice to handle this automatically for the users, but this would be a workaround.

**Comment by nzoschke** [comment]
Yeah I liked the design discussion around automatically handling it.

But setting this explicitly on apps is the simple way to go for now. We also plan to improve silently failing/churning deployments here:

https://github.com/convox/rack/issues/68

Going to close this one. Thanks for the feedback all.
