### ISSUE TITLE
Datastore Service ParameterGroups

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#461]
@idyll opened my eyes to tuning RDS Parameters on https://github.com/convox/rack/issues/386. A way to tune MaxConnections landed in https://github.com/convox/rack/pull/428:

```
$ convox services add postgres --max-connections={DBInstanceClassMemory/15000000}
```
## Implementation Goals
- Make it easy to discover and tune key parameters for data stores
- Attempt to remove some complexity from ParameterGroups. There are too far too many, and the ones that are derived from other ones are very very hard to understand
- Lean on CloudFormation as much as possible for parameter validation and application.
## Key Parameters
- What are the most important parameters we know of for postgres?
- What are the most important parameters we know of for mysql?
- What are the most important parameters we know of for redis?

**Comment by dlanger** [comment]
@nzoschke First thought for important redis parameters (in decreasing order) include `maxclients`, and `maxmemory-policy`, `reserved-memory`, `min-slaves-to-write`, and `appendfsync`.

I'd also be interested in exposing (in an intentional and optional way) all the messiness that is ParamaterGroups. I like the idea of picking the most common/important ones and exposing them in a friendly form, but at the same time I think it's important that there's a way to tune any of them (if I so choose and know what I'm doing). 

If we start with the "friendly" ones being something like this:
```
redis --max-connections=10 --multi-az --eviction-policy=lru
```
The following two ideas come to mind...

##### Allow arbitrary parameters on the command-line
```
redis --eviction-policy=lru --param maxmemory-samples=3 --param tcp-keepalive=1
```
Then map all the key-value pairs from the `--param` entries directly into the JSON `properties` [blob](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-parameter-group.html), with them overriding any of the "friendly" ones.

##### Allow arbitrary parameters in a file
```
redis --eviction-policy=lru --params redis-dev.yaml

$ cat redis-dev.yaml
params:
    maxmemory-samples: 3
    tcp-keepalive: 1
```
I'd like this more, as if I'm doing complex parameter setting I'm going to want to have it stored somewhere auditable, and done in a way that I can work with my colleagues on what values to use.

**Comment by nzoschke** [comment]
Thank you. This feature will benefit greatly from your real-world expertise with elasticache!

**Comment by ddollar** [comment]
:+1: to adding the `--param` option for services. Let's avoid implementing the parameters-in-file just yet as I think there might be a way to do this that stays within `docker-compose.yml`

**Comment by matthewford** [comment]
> What are the most important parameters we know of for postgres

Encryption

**Comment by ddollar** [comment]
I think the best thing to do is still handle these params on a case-by-case basis.
