### ISSUE TITLE
docker-compose 'extends' does not work as expected with "convox start"

### ISSUE THREAD

**Issue by peterlauri** [convox/rack#480]
Based on docker documenation:

https://docs.docker.com/compose/compose-file/#extends
https://docs.docker.com/compose/extends/#extending-services

One should be able to specify inheritance, using "extends" parameter. This my setup to display the problem:

```
# Dockerfile
FROM ubuntu:14.04
CMD ["env"]

# docker-compose.yml
main:
  build: .
  environment:
    ENV1: hello_world

# docker-compose-local.yml
main:
  extends:
    service: main
    file: ./docker-compose.yml
  environment:
    ENV2: pjotr2
```

Result using normal docker-compose (both ENV1 ENV2 are present)...

```
# docker-compose -f docker-compose-local.yml run main
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=921574e0e0b4
TERM=xterm
ENV2=pjotr2
ENV1=hello_world
HOME=/root
```

Result using **convox start -f docker-compose-local.yml**:

```
#  convox start -f docker-compose-local.yml
main   | running: docker run -i --name convox-compose-extends-bug-main -e ENV2=pjotr2 convox-compose-extends-bug/main
main   | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
main   | HOSTNAME=30227175b2cb
main   | ENV2=pjotr2
main   | HOME=/root
```

**Comment by mattmanning** [comment]
`extends` should also be supported for `convox build|deploy` as well.

**Comment by mwarkentin** [comment]
This would be useful for us - we're starting to use a pattern where we have `docker-compose.yml` to define the application when deployed to a rack, and `docker-compose-local.yml` to define the application when run locally. Right now this involves a decent amount of duplication, that we could really cut down if we could extend `docker-compose.yml` with our local changes.

**Comment by landakram** [comment]
This would be useful for us too. For context, we currently keep a full description of a stack in `docker-compose.yml`, which we use for both production and development (the environment variables differ). 

This means that when we deploy a repo for the first time, however, we have to do `convox scale process --count=-1` for every process that is a Convox service (i.e. RDS databases) or other cloud service. This isn't a huge inconvenience, but it isn't realy automatable, and it feels cleaner to not deploy those processes to begin with since we _know_ they'll be hosted elsewhere. 

With proper extends support, we could maintain a `docker-compose-local.yml` without having to duplicate, as @mwarkentin describes.

**Comment by jessepollak** [comment]
Another use case is that we have a set of environment variables which we want to specify in development, but don't want to have to worry about setting in production. If the override functionality mimicked the docker-compose standard, then we could specify development environment variables in `docker-compose.overide.yml` without specifying them in `docker-compose.yml`.

**Comment by dalberto** [comment]
Another use-case for `extends` is having different volume mounts between production and development. For example, I currently have a `docker-compose.yml` that has a `volumes` section like this:

```
volumes:
      - ./my-local-source:/app
      - /app/node_modules
```

This is a workaround for node apps to ensure that `node_modules` inside the container is not overridden with an empty directory. There are other workarounds but this is the simplest and most elegant I've found so far.

When deploying, I *don't* want `/app/node_modules` to become a shared directory using EFS. Having the ability override this and other parts of the manifest would be super useful.

**Comment by ddollar** [comment]
@dalberto If you use the built-in code sync you will not need the volume for code and won't mask out your node_modules directory

Ideally you would not need to maintain separate manifests for development and production. Would love to hear a bit more details about why folks are finding the need to do this so we can take them into account in the solution.

**Comment by dalberto** [comment]
@ddollar thanks for responding. I am currently using Docker for Mac's solution for volume mounting. While it has its share of problems, I have found it to be more responsive than Convox's code sync. 

Additionally, I like to keep as close to the built-in Docker features as possible especially since a lot of other tooling tends to integrate with the built-in features. For example, I would not be able to use JetBrain's PyCharm debugger with Convox , while I _can_ use it with `docker-compose`. There are a few other examples I can think of where the same thing applies. For this reason I don't see myself or my team using features in Convox that mirror "first-party" Docker features -- it locks us out of the broader Docker ecosystem.

Regarding the need for different manifests for different environments, I initially agreed with you -- there _should_ only be one manifest file. However, I've found a handful of compelling use-cases where I think the single manifest feels like a big constraint. Besides the aforementioned volume mounting use-case, it would be very useful to define services for different environments. Specifically, it is highly unlikely that I would use a containerized database in production, while it is completely reasonable to do so for local development or for ephemeral apps (see below). Sure, I can scale down the different process types on production (this is what I've been doing so far) but this seems pretty inefficient and consumes quite a bit of time (i.e. we shouldn't be wasting time provisioning ELBs and other resources for services that are going to be eliminated anyway). 

Another use-case is related to volume mounting but not in the same way as code sync. I admit that this may be a little bit more esoteric. We tend to use Convox for ephemeral apps. We have found that creating new apps is very quick and easy with Convox, so we tend to create short-lived apps that are "forks" of other apps (e.g. a particular feature branch, or a particular staging environment). This is really useful for our team because it allows us to experiment and iterate at a much faster pace. It also enables us to set up isolated testing environments for customers (I can expand upon this use-case via DM). These ephemeral apps actually benefit from volume mounts that use EFS. These volume mounts are different in that we just need to persist some data (e.g. the Postgres directory) and it has nothing to do with code. Locally, we would like these mounts to refer to a local path, but on each Rack this needs to be an absolute path. Having more than one manifest would facilitate this without resorting to multiple files and a lot of copy-and-paste.

**Comment by dalberto** [comment]
We've actually run into another use-case.

Some (most?) hosted continuous integration services have limitations on the ports that a process can expose. Our `docker-compose.yml` for convox expose ports 80 and 443 publicly. This conflicts with our CI constraints. 

If convox supported multiple compose files, we could have a base manifest that makes no assumptions about port mappings and then have a `convox.yml` and a `test.yml` that extends the base manifest appropriately. At the moment, we've had to resort to copy and pasting the manifest in order to support the use-case but this obviously makes it harder to maintain our environment configuration.

**Comment by dalberto** [comment]
Sorry to keep harping on this but we continue to encounter more use-cases as we begin using Convox more and more and so far this has proven to be the best forum for discussing use-cases around multiple, composable manifests. Let me know if there is a superior forum or communication channel.

Another use-case we have is setting different deployment strategies for different environments. For example, in a test or development environment, it would be advantageous to have very fast deployments, even if some downtime is incurred (e.g. setting `convox.deployment.minimum` to 50 or even 0), while in a production environment that would not be the case. Having a `docker-compose.prod.yml` and a `docker-compose.dev.yml` that convox understands would make this feasible.

**Comment by spencerhakim** [comment]
Any movement on this? It's been marked as a priority since July, but there's been minimal discussion.

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [docker-compose extends](https://trello.com/c/tCfeJB44/440-docker-compose-extends)

**Comment by ddollar** [comment]
Closing this for now. We're working on a design around application profiles that should cover this without the strange proliferation driven by `extends:`

**Comment by kidbrax** [comment]
Do you have anymore info on these application profiles? It would be nice if we could just pass a single environment variable that then pulled in all the right config.

**Comment by twe4ked** [comment]
@ddollar Is there a new issue I can subscribe to to track this?

**Comment by kevinhuang12345678** [comment]
if "docker-compose extends" is not supported in convox yet, any workaround? thanks.

Regards,
Kevin
