### ISSUE TITLE
Hardcoded strings in LabelsByPrefix

### ISSUE THREAD

**Issue by ddollar** [convox/rack#577]
https://github.com/convox/rack/blob/master/api/models/manifest.go#L183
https://github.com/convox/rack/blob/master/api/models/manifest.go#L196

**Comment by mwarkentin** [comment]
If you press `y`, Github will give you a perma-link to the code so that future changes don't mess up your links (I know I tried looking at a similar issue a while ago and the links to the code lines didn't make sense anymore):

* https://github.com/convox/rack/blob/ee7f1b9e88340a3f104af71b6ba01fdacb1e5a3c/api/models/manifest.go#L183
* https://github.com/convox/rack/blob/ee7f1b9e88340a3f104af71b6ba01fdacb1e5a3c/api/models/manifest.go#L196

**Comment by ddollar** [comment]
Good tip, thanks :)
