### ISSUE TITLE
Configure ELB health-checks

### ISSUE THREAD

**Issue by dlanger** [convox/rack#613]
Similar to #594 (in the vein of "more ELB configuration options"), it'd be nice if we could configure ELB health-checks. 

Right now, they default to a TCP connection to the exposed port. This works as a lowest-common-denominator, but misses out on a lot of the power of ELB health-checks. In an ideal world, I'd be able to pick an HTTP health-check and specific a specific path to use (which I could point at [`health_check`](https://github.com/ianheggie/health_check), [`django-watchman`](https://github.com/mwarkentin/django-watchman), etc.)

Open questions:
* Where do we specify the path to health-check? Probably a `docker-compose.yaml` label
* Should the health-check [type](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-healthchecks.html) be individually selectable (thought a `docker-compose.yaml` label), or should it be coupled to the ELB protocol?

@nzoschke @ddollar Thoughts?

**Comment by ddollar** [comment]
We can probably do this with more labels, similar to https://convox.com/docs/load-balancers/

**Comment by shin-nien** [comment]
Also being able to configure the timeout, intervals and thresholds would be useful too.

I'm deploying a fairly heavy java app that takes a while to start up so at the moment I'm re-configuring the ELB once it's created so my app can start without getting killed.

**Comment by nzoschke** [comment]
The configuration for every app stack (ELB, TaskDefinition, and Services) is in `app.tmpl`. The health check for each ELB is here:

https://github.com/convox/rack/blob/master/api/models/templates/app.tmpl#L357

This is a CloudFormation template that we run it through Go templating to make resources for every process type.

I think you'll want to Parameterize the Timeout or UnhealthyThreshold. 

You can follow the same pattern as `{{ upper $balancer.ProcessName }}Port{{ .Balancer }}Protocol`. It has a Parameter for every process type with a default value here:

https://github.com/convox/rack/blob/master/api/models/templates/app.tmpl#L282

Which can be used instead of the hard coded `3` here:

https://github.com/convox/rack/blob/master/api/models/templates/app.tmpl#L361

You can run the rack API on your laptop following the Development.md guide. Make sure to see the https://github.com/convox/rack/blob/master/Development.md#infrastructure-changes section. When you make changes to app.tmpl, you then need to run `make templates`, then wait for the api server to reload, then you can:

```
# login to development API with your changes
$ convox login localhost

# deploy the app to apply the new CF stack template
$ convox deploy

# try changing the new parameter and see how it affects your app
$ convox apps params set WebTimeout=20
```

**Comment by nzoschke** [comment]
If you look at the [Load Balancers doc](https://convox.com/docs/load-balancers/) you see we have a pattern where a docker-compose.yml label can control load balancer settings.

You should be able to follow the same pattern in release.go where the `protocol` label is parsed and automatically set as an app stack parameter:

https://github.com/convox/rack/blob/master/api/models/release.go#L189

**Comment by contra** [comment]
This can be closed now, no?

**Comment by mwarkentin** [comment]
I think so.
