### ISSUE TITLE
Add option to convox logs to replay some history

### ISSUE THREAD

**Issue by whatupdave** [convox/rack#66]
Right now `convox logs` starts tailing from latest. An option to go back some time or some amount of lines would be awesome.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nfobjjkf&#x2F;78-convox-logs-shows-a-bit-of-history"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Convox logs shows a bit of history</a>

**Comment by nzoschke** [comment]
This will be a very nice enhancement, thanks for the suggestion.

The current behavior is due to using the LATEST ShardIteratorType as part of the Kinesis GetRecords, which is much easier to implement (and reason about) than the sequence number stuff.

Recently I introduced CloudWatch Logs as another system logs are being sent to. I would like to ultimately rely solely on CloudWatch Logs and remove Kinesis.

- [ ] Move `convox logs` over to stream from the app's CloudWatch LogGroup and its many LogStreams
- [ ] Use [GetLogEvents StartTime](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_GetLogEvents.html#CWL-GetLogEvents-request-StartTime) parameter to include a bit of history

**Comment by bobzoller** [comment]
Exciting! Thanks Noah.

**Comment by nzoschke** [comment]
This is solved with the migration to cloudwatch logs and the `convox logs --since` option. Docs: https://convox.com/docs/logs/
