### ISSUE TITLE
Convox run --release should have the proper environment

### ISSUE THREAD

**Issue by ddollar** [convox/rack#669]
See the last few comments on #526

**Comment by beedub** [comment]
This seems like a major issue on the surface. I looked into fixing this but found it not trivial to fix.

The current code pulls the env from the ecs task definition container env, but task definitions are not generated for releases that haven't been promoted yet.

Could convox comment with their thoughts on how they'd fix this and considerations when thinking about or fixing this issue?

**Comment by nzoschke** [comment]
Thanks for taking a look, I just applied the priority label because I want to get this fixed so we can do more release workflow stuff.

Using `convox env` to add/remove/update environment variables creates a new release record and release ID, and writes secrets to S3 encrypted with KMS. `convox release` decrypts this data and passes it through to cloudformation to create a task definition.

So it is possible to get the right environment even when a TaskDefinition doesn't exist.

With the right env, we can continue to run one-offs with `docker run` API calls.

Yeah, the current implementation will need some more care. To fix this I would:

* Move `convox run --release` over to the  the S3Get / Decrypt path.
** The implementation here can be factored out, ideally into a new provider interface method like `EnvironmentGet(app, releaseId string)`
* Review app.RunAttached to use the right environment and docker images for the release id
** Ideally move this into a new provider interface method like `ProcessRun(app, process, releaseId, command string, height, width int)`

**Comment by nzoschke** [comment]
Though a tactical fix just for getting the environment from S3 over ECS would be a very pragmatic approach too.

Finally, I could also see a design where creating a new release always creates a new TaskDefinition so we could delegate the run to ECS. But that's an even bigger change.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Ue5ekEuk&#x2F;280-convox-run-release"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> convox run --release</a>

**Comment by MiguelMoll** [comment]
> So it is possible to get the right environment even when a TaskDefinition doesn't exist.

Seems this is accurate for variables set via `convox env set`. But other variables that are set by the Rack API (e.g `$RELEASE`) or `convox services` are only available via the task definition. One of those variables (e.g `$REDIS_HOST`) might be needed for a process to complete successfully.

Two possible solutions is going the task definition route or saving all environment variables in S3.
