### ISSUE TITLE
removing convox.port.NNN.secure label does not negate Secure parameter

### ISSUE THREAD

**Issue by ddollar** [convox/rack#711]
Removing this label should set the `Secure` parameter to `No`

**Comment by mwarkentin** [comment]
Do you differentiate between it being there and then being removed (so set `Secure=No`), vs. just never being there? 

eg. if I had set `convox apps params set Secure=Yes`, but haven't added the label in `docker-compose.yml` - would my setting get wiped the next time I deployed?

**Comment by ddollar** [comment]
I think no. You're right that there might be a potential overwrite of a manually-set parameter here. Given that the people who want to set the parameter have an easy way to do so by setting the label (and they really need to in order to get the right behavior with convox start) I think that's OK. We've already had one person be bit by the label not getting set back to `No` after removing the label.

**Comment by mwarkentin** [comment]
Yep, I definitely think there are a lot of benefits to triggering off of the label, instead of manually setting params:

* Explicit
* Automatic - works on first deploy
* Closer to infrastructure-as-code - can be checked in, reviewed, etc.

On the other side - if someone *has* set this up by manually setting params - there needs to be a strong warning to make sure that they update before deploying.

Have you considered adding a deprecation policy for things like this? Either making the change, but adding the extra logic to check existing params and warn / manage backwards compatibility for a couple of rack releases? Or just putting the warning in place first, and then implementing in some period of time?

This would definitely add complexity to the code, but could make migrations across breaking changes like this a lot smoother - especially for people who aren't closely following convox development.

**Comment by ddollar** [comment]
Definitely. One thing I would love to do is use the CloudFormation changeset APIs to allow you to preview all changes that are going to happen as part of a deploy

**Comment by mwarkentin** [comment]
True, that would help.

**Comment by ddollar** [comment]
Closing for now
