### ISSUE TITLE
Better rolling of autoscale groups

### ISSUE THREAD

**Issue by ddollar** [convox/rack#79]
We can use resource signalling to trigger a smoother roll of the autoscale groups. If combined with a bit more pause time we should be able to roll without app downtime.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-ecs.html

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JWMk511S&#x2F;188-better-rolling-of-autoscale-groups"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Better rolling of autoscale groups</a>

**Comment by jordan-thoms** [comment]
Seems like it'd also be helpful if the autoscaling group used a health check that ensured the instance was running the ECS agent and joined the cluster rather than just booted, as it takes a few minutes to join and it's a little hair raising if we start shutting down the next instance before the tasks have had a chance to move to the new one.

**Comment by csquared** [comment]
fix proposed #107

**Comment by csquared** [comment]
Fixed!
