### ISSUE TITLE
`convox start` should warn if vars in .env don't appear in .docker-compose.yml

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#800]
It would avoid confusing situations as in https://github.com/convox/rack/issues/799

In that example `SOME_VAR=some_val` was set in `.env`, but `SOME_VAR` did not appear in `docker-compose.yml`, so it didn't get passed to the container. It would have been nice to get a warning from `convox start` like: "WARNING: Environment variable SOME_VAR appears in .env but is not declared in docker-compose.yml"

**Comment by awsmsrc** [comment]
my 2c here is that it is weird that it needs to be in both places in the first place as this is different to the docker-compose native behavior: https://docs.docker.com/compose/environment-variables/

**Comment by mwarkentin** [comment]
Another issue with some questions around docker compose and .env interaction from a while ago: https://github.com/convox/rack/issues/403

**Comment by jordansexton** [comment]
As much as I was confused by this behavior, I think it's a good thing that explicit declaration of the variables to be passed through is required. I think a warning on finding variables in `.env` that aren't in `docker-compose.yml` would be sufficient.

Alternatively or additionally, supporting the `env_file` directive would be useful, since it provides another way of making the declaration explicit (without requiring declaration in two places).

**Comment by hulbert** [comment]
Couple more cents, my colleague (being familiar with docker compose) tried to use `env_file` to no success when first trying convox.

**Comment by nzoschke** [comment]
This is a pretty fundamental part of the onboarding experience. I don't have a design input right now but I'd like to see this resolved up and documented.
