### ISSUE TITLE
Instances overloaded by convox builds

### ISSUE THREAD

**Issue by beedub** [convox/rack#928]
The convox api uses the underlying host's docker daemon to build images. If there are a sufficient number of concurrent builds, then the resources on the box can get saturated, adversely affecting every other process (including other running tasks).

Could the api container just run its own docker daemon? If so, then its resource usage would match what one would expect from the task definition's cpu and memory constraints

**Comment by skwp** [comment]
We have proposed building externally, pushing to an ECR repo, and then using `image` in the docker-compose to read from that repo. However convox's default behavior if you do that will be to read the image and re-push it to the per-app repo (which is ok, but a little extra overhead). On top of that there appear to be some caching woes where it won't always pick up the latest changes. We are still experimenting to see if we can dynamically tag the image with a unique tag and then `sed` out the `image` in the docker-compose file to have it pick up the latest changes. 

But I think at the end of the day convox would ideally cleanly support taking images not built by convox so that the build and deploy steps can be decoupled. Most real production environments probably won't want to build on the cluster where apps are running.

**Comment by ddollar** [comment]
Fixed by #1231
